### PR TITLE
Updated the dependencies for 1.14

### PR DESCRIPTION
**Pull request by houshengbo**

### CODE REVIEW

**Review by upodroid — APPROVED** [review]
/override "style / Golang / Boilerplate Check (go)"
/override "style / Golang / Boilerplate Check (sh)"
/override "style / Golang / Do Not Submit"
/override "style / Golang / Lint"
/override "style / suggester / shell"
/override "style / suggester / yaml"

/hold cancel when you are ready to merge it

**Comment by dsimansk** [comment]
/override "style / Golang / Do Not Submit"

**Pull request merged**
